### ISSUE TITLE
docker container [feature request]

### ISSUE THREAD

**Issue by x0rzkov** [LdDl/go-darknet#1]
Hi,

Hope you are all well !

It would be interesting to have a docker container for building and linking darknet. Isn't it ?

Cheers,
X

**Comment by LdDl** [comment]
Hello)

Actually, I was thinking to make something like *.sh script, where we can play with flags for building Darknet (such as GPU=..., CUDA=.... and etc.).
But docker container is interesting too. I'll thiknk about that.

**Comment by x0rzkov** [comment]
I have already dockerized your library, do you want me to make a pull request ?

**Comment by LdDl** [comment]
> I have already dockerized your library, do you want me to make a pull request ?
I do, it's a good idea.
make a PR, and I'll look at it)

**Comment by x0rzkov** [comment]
It is done

**Comment by x0rzkov** [comment]
I have an error for the gpu version

# github.com/LdDl/go-darknet
/usr/bin/ld: warning: libcuda.so.1, needed by /usr/lib/libdarknet.so, not found (try using -rpath or -rpath-link)
/usr/lib/libdarknet.so: undefined reference to `cuCtxGetCurrent'
collect2: error: ld returned 1 exit status
but I have declared the envs
LIBRARY_PATH=$LIBRARY_PATH:/usr/local/cuda-10.0/compat/
where libcuda.so.1 is located.

Shall I move the files somewhere else ?

**Comment by svaichu** [comment]
@x0rzkov did u manage to solve this issue?
