### ISSUE TITLE
[BUG] memory leak on perform_network_detect C function

### ISSUE THREAD

**Issue by arthurhenrique** [LdDl/go-darknet#15]
**Describe the bug**
Memory doesn't free at the [perform_network_detect](https://github.com/LdDl/go-darknet/blob/master/network.c#L9-L25) function. Precisely at the `network_predict` and `get_network_boxes` calls.

**To Reproduce**

Software Versions:
```
go version 1.15.6
go-darknet v1.3.0
```

Model:
```
yolov4-tiny.cfg
yolov4_tiny.weights
https://github.com/AlexeyAB/darknet/archive/darknet_yolo_v4_pre.zip 
```

Snnipet:
```golang
imgDarknet, err := darknet.Image2Float32(src)
if err != nil {
    return nil, err
}
	
dr, err := Network.Detect(imgDarknet)
if err != nil {
     return nil, err
}
```

**Comment by LdDl** [comment]
We were used to call C network_predict_ptr() and then switched to network_predict():
https://github.com/LdDl/go-darknet/commit/420a74769d1d71b70eeda5cdedb3799e2d1825c7

I'll take a look at this with valgrind and pprof

**Comment by LdDl** [comment]
running valgrind:
```shell
valgrind --log-file=val.log --track-origins=yes --leak-check=full ./main --configFile=../yolov4.cfg --weightsFile=../yolov4.weights --imageFile=../sample.jpg
```

output log file:
[val.log](https://github.com/LdDl/go-darknet/files/5886512/val.log)

```shell
==44520== LEAK SUMMARY:
==44520==    definitely lost: 23,608 bytes in 958 blocks
==44520==    indirectly lost: 530,944 bytes in 1,037 blocks
==44520==      possibly lost: 1,593,644 bytes in 12,199 blocks
==44520==    still reachable: 460,732,964 bytes in 467,721 blocks
```

**Comment by LdDl** [comment]
https://github.com/LdDl/go-darknet/commit/165e59aaf39adb42a12b19bb2b7612224856bd6c#diff-6f0cc157b676e67fdf8cc73ae7890fc04361c23e9552d345f6df5b8c23e496f4L64

Calling "defer" was not a gread idea in base example.

**Comment by arthurhenrique** [comment]
> Is this really bindings mistake? What do you think?
> @arthurhenrique

I think it is an internal problem of the darknet library. I made a binding to `free_network_ptr`, but the memory problem still remains...

**Comment by arthurhenrique** [comment]
> btw, calling "defer" was not a gread idea in base example

I remove the defer too, thank you! 
Just for curiosity. Why is this a not great idea?

**Comment by LdDl** [comment]
> > btw, calling "defer" was not a gread idea in base example
> 
> I remove the defer too, thank you!
> Just for curiosity. Why is this a not great idea?

Because you may want to write something like this:
```go
for t := 0; t < 1000; t++{
	imgDarknet, err := darknet.Image2Float32(src)
	if err != nil {
		panic(err.Error())
	}
	defer imgDarknet.Close()
	//
	// Some Code
	//
	time.Sleep(100*time.Millisecond)
}
```
... and this will eat yours RAM pretty fast.
"defer" calls not working in loops. If you want to user "defer", you should wrap it with some function.
[Here](https://github.com/LdDl/go-darknet/blob/master/example/rest_example/main.go#L70) is example where we used defer call and it's correct since it wrapped with func(w http.ResponseWriter, req *http.Request).
The "defer" calls lives on stack and then executed in a oposite order (reverse) at the end of wrapping function

**Comment by arthurhenrique** [comment]
Oh, sorry! `imgDarknet.Close()` It's already wrapped. 👍
