### ISSUE TITLE
[BUG] Build error on golang:1.15.7-alpine3.13 docker image

### ISSUE THREAD

**Issue by arthurhenrique** [LdDl/go-darknet#17]
**Describe the bug**
`#20 4.538 vendor/github.com/LdDl/go-darknet/network.go:61:2: could not determine kind of name for C.free_network_ptr`

**To Reproduce**
Docker: `golang:1.15.7-alpine3.13`
Run: CGO_ENABLED=1 go install -v -a --installsuffix --ldflags="-s"

**Expected behavior**
`#20 4.538 vendor/github.com/LdDl/go-darknet/network.go:61:2: could not determine kind of name for C.free_network_ptr`

**Comment by arthurhenrique** [comment]
I think you should rollback this https://github.com/LdDl/go-darknet/pull/16/commits/40df8cce9143f5f46d4ea82482c96dd4ca32168b

**Comment by LdDl** [comment]
I forgot that we have had docker-build :)
Will check it later.
Have not that much time due the regular job to be honest...
