### ISSUE TITLE
[BUG] 为什么检测一次很慢，大概再6-10秒左右，yolov5大概再20ms左右

### ISSUE THREAD

**Issue by a97077088** [LdDl/go-darknet#18]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior

**Expected behavior**

**Expected behavior**

**Describe the solution you'd like and provide pseudocode examples if you can**

**Additional context**

**Comment by LdDl** [comment]
@a97077088 
Hello
Can you edit your message and describe what probem is?

**Comment by LdDl** [comment]
So after google translate:
```
Why is the detection very slow once, about 6-10 seconds, and yolov5 about 20ms
```

Are you using CPU build?

**Comment by a97077088** [comment]
yes

**Comment by LdDl** [comment]
@a97077088 
So you can't expect that CPU version can perform detection in 20ms. I've never seen this done via any not-tiny YOLO version.
