### ISSUE TITLE
crop the bounding box content

### ISSUE THREAD

**Issue by x0rzkov** [LdDl/go-darknet#2]
Hi,

Again ! :-)

I was wondering if there is a function to crop the content of the bounding box in separate pictures ?

Cheers,
X.

**Comment by LdDl** [comment]
Hello there!
I've made PR in example main.go file:
https://github.com/LdDl/go-darknet/blob/master/example/main.go#L84

It uses https://github.com/disintegration/imaging (MIT license)

Convert darknet's bbox to image.Rectangle of standart library
```go
minX, minY := float64(bBox.StartPoint.X), float64(bBox.StartPoint.Y)
maxX, maxY := float64(bBox.EndPoint.X), float64(bBox.EndPoint.Y)
rect := image.Rect(round(minX), round(minY), round(maxX), round(maxY))
```

Crop *image.NRGBAfrom image via provided rect (disintegration's library must be used)
```go
rectcropimg := imaging.Crop(imgSrc, bbox)
```

And then you are goot to go with saving *image.NRGBA to file:
```go
f, err := os.Create(fname)
if err != nil {
	return err
}
defer f.Close()
err = jpeg.Encode(f, rectcropimg, nil)
if err != nil {
	return err
}
```

**Comment by x0rzkov** [comment]
awesome, will try just now

**Comment by LdDl** [comment]
glad to know it works :)
closing
