### ISSUE TITLE
rest api example

### ISSUE THREAD

**Issue by x0rzkov** [LdDl/go-darknet#4]
Hi,

Hope you are all well !

Is it possible to provide an example of rest api receiving either url or body image ? That would be awesome addition.

Cheers,
X

**Comment by x0rzkov** [comment]
I made a quick example https://gist.github.com/x0rzkov/42e6bc596cc59c702171c2aabc0664ee

It is cropping the largest area detected if it is a car. In fact, it is tailored to my needs but we can make something more generic. Open to the discussion.

How do you see it ?

**Comment by LdDl** [comment]
Interesting.

But. I don't think it is good idea to use REST for such purpose. I find it more "correct" to use gRPC (for example)
Also I'd prefer to send bbox params to client (JavaScript) and make crops/renders on client side.

p.s. by the way I'm working on gRPC listening server right now ;)

**Comment by x0rzkov** [comment]
Can you help me to fix the gpu issue first ? I need to make some tests

**Comment by x0rzkov** [comment]
My version has a big problem, it is multi-threading. I tried the gpu version with 24 queries per seconds and it crashes.

Do you know how we can make the model to be multi-threaded ?

**Comment by LdDl** [comment]
related issues in AlexeyAB's Darknet:
https://github.com/AlexeyAB/darknet/issues/4356
https://github.com/AlexeyAB/darknet/issues/3906

My bet, that the best solution (currently) would be make lock via [mutexes](https://tour.golang.org/concurrency/9) for *YOLONetwork.
Or maybe make a queue (but it can grow very fast) via channels.

p.s. https://twitter.com/GreatAkcium

**Comment by x0rzkov** [comment]
I cannot DM you, you ll have to follow me and send the first DM.

I am testing a couple of things on mutexes. Keep u in touch
